version: "3.8"

services:
  fastapi:
    image: postgres:14-alpine
    ports:
      - 5438:5432
    volumes:
      - 'github_analytics:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres

volumes:
  github_analytics:
