version: "3.8"

services:
  postgres:
      image: postgres:14-alpine
      container_name: postgres
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_NAME: postgres
      volumes:
        - "github_analytics_prod:/var/lib/postgresql/data"
  app:
    build:
      dockerfile: deploy/Dockerfile
      context: ..
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: bash -c "./deploy/wait-for-it.sh postgres:5432 
                      && alembic upgrade head && cd api
                      && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
    restart: always
    expose:
      - 8000

volumes:
  github_analytics_prod: