on:
  push:
    branches:
      - master
    paths-ignore:
      - 'scheduled_parser/**'
      - '.github/workflows/deploy-serverless-function.yml'

env:
  IMAGE_NAME: "github-analytics-app"
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: fetch repository code
        uses: actions/checkout@v4

      - name: setup Python3:11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required dependencies
        run: pip install poetry && poetry config virtualenvs.create false && poetry install

      - name: run tests
        run: pytest -s -v
#      - name: enter in Docker container and run tests
#        run: docker-compose -f './deploy/docker-compose.test.yml' exec app ./deploy/wait-for-it.sh postgres:5432 && pytest -s -v

  migrations:
    runs-on: ubuntu-latest

    steps:
      - name: fetch repository code
        uses: actions/checkout@v4

      - name: run Docker container and make migrations
        run: docker run --rm
              -e DB_NAME=${{ secrets.DB_NAME }} 
              -e DB_USER=${{ secrets.DB_USER }} 
              -e DB_HOST=${{ secrets.DB_HOST }}
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} 
              -e DB_PORT=${{ secrets.DB_PORT }} 
              $(docker build -f './deploy/Dockerfile' -q .) 
              alembic upgrade head

  deploy-serverless-container:
    runs-on: ubuntu-latest
    needs:
      - tests
      - migrations

    steps:
      - name: fetch repository code
        uses: actions/checkout@v4

      - uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          DOCKERFILE_PATH: "./deploy/Dockerfile"
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: github-analytics-app
          folder-id: ${{ secrets.FOLDER_ID }}
          revision-service-account-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
          revision-cores: 1
          public: true
          revision-memory: 256Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          revision-execution-timeout: 600
          revision-env: |
            DB_PORT=${{ secrets.DB_PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
