on:
  push:
    branches:
      - master
    paths:
      - 'scheduled_parser/**'
      - '.github/workflows/deploy-serverless-function.yml'

jobs:
  deploy-serverless-function:
    runs-on: ubuntu-latest

    steps:
      - name: fetch repository code
        uses: actions/checkout@v4
      - name: deploy cloud function
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'github-api-parser'
          runtime: 'python312'
          memory: '256Mb'
          entrypoint: 'index.handler'
          source-root: './scheduled_parser'
          service-account: ${{ secrets.SERVICE_ACCOUNT_ID }}
          execution-timeout: '600'
          environment: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} 
            DB_USER=${{ secrets.DB_USER }} 
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }} 
            DB_PORT=${{ secrets.DB_PORT }} 
            DB_NAME=${{ secrets.DB_NAME }}
